const links = {
    'id':[
        'cTkKdCyTj3GAvZE8',
        'eRQPF63KrVuvVGhV',
        'hjEjRTF9uSJrvj4w',
        'LbiGcPFQTsx45iZ5'
    ],
    'title':[
        '冒険サーバー(仮称)用mod',
        '冒険サーバー(仮称)用mod(追加)',
        '冒険サーバー(仮称)用mod(追加part2:AoA,豆腐,XPBank,銃,optifine)',
        '冒険サーバー(仮称)用mod(追加part3:InvTweaks)'
    ],
    'link':[
        [
            'https://www.curseforge.com/minecraft/mc-mods/iron-chests/download/3405717/file',
            'https://www.curseforge.com/minecraft/mc-mods/jei/download/3480853/file',
            'https://www.curseforge.com/minecraft/mc-mods/gemsplusplus/download/3462347/file',
            'https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice/download/3391266/file',
            'https://www.curseforge.com/minecraft/mc-mods/geckolib/download/3448099/file',
            'https://www.curseforge.com/minecraft/mc-mods/curios/download/3456953/file',
            'https://www.curseforge.com/minecraft/mc-mods/geolosys/download/3342071/file',
            'https://www.curseforge.com/minecraft/mc-mods/patchouli/download/3459118/file',
            'https://craft.mystia.org/InstantLava/InstantLava_Forge1.16.1-latest.jar',
            'https://www.curseforge.com/minecraft/mc-mods/forgiving-void/download/3330716/file',
            'https://www.curseforge.com/minecraft/mc-mods/serene-seasons/download/3429973/file',
            'https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay/download/3052146/file',
            'https://www.curseforge.com/minecraft/mc-mods/special-ai/download/3391946/file',
            'https://www.curseforge.com/minecraft/mc-mods/kleeslabs/download/3222119/file',
            'https://www.curseforge.com/minecraft/mc-mods/ikkatsuhakai-axe/download/3119344/file',
            'https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/download/3289916/file',
            'https://www.curseforge.com/minecraft/mc-mods/netherportalfix/download/3098229/file',
            'https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge/download/3469837/file',
            'https://www.curseforge.com/minecraft/mc-mods/architectury-forge/download/3462013/file',
            'https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge/download/3460043/file',
            'https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge/download/3476854/file',
            'https://www.curseforge.com/minecraft/mc-mods/item-filters-forge/download/3376819/file',
            'https://www.curseforge.com/minecraft/mc-mods/wall-jump/download/3193207/file',
            'https://www.curseforge.com/minecraft/mc-mods/everlastingabilities/download/3420213/file',
            'https://www.curseforge.com/minecraft/mc-mods/cyclops-core/download/3474910/file',
            'https://www.curseforge.com/minecraft/mc-mods/antique-atlas/download/3398190/file',
            'https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition/download/3420107/file',
            'https://www.curseforge.com/minecraft/mc-mods/morpheus/download/3215383/file',
            'https://www.curseforge.com/minecraft/mc-mods/rpg-hud/download/3172784/file',
            'https://www.curseforge.com/minecraft/mc-mods/inventory-spam/download/3242399/file',
            'https://www.curseforge.com/minecraft/mc-mods/better-diving/download/3425106/file',
            'https://www.curseforge.com/minecraft/mc-mods/appleskin/download/3395800/file',
            'https://www.curseforge.com/minecraft/mc-mods/better-foliage/download/3409419/file',
            'https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings/download/3288746/file',
            'https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/download/3311352/file',
            'https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/download/3452303/file'
        ],
        [
            'https://www.curseforge.com/minecraft/mc-mods/storagebox-mod/download/3119354/file',
            'https://www.curseforge.com/minecraft/mc-mods/clickmanaita/download/3205045/file'
        ],
        [
            'https://cdn.discordapp.com/attachments/633620196862590976/897015973926801428/OptiFine_1.16.5_HD_U_G8.jar',
            'https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine/download/3378340/file',
            'https://www.curseforge.com/minecraft/mc-mods/tofucraftreload/download/3454680/file',
            'https://www.curseforge.com/minecraft/mc-mods/global-xp/download/3293040/file',
            'https://www.curseforge.com/minecraft/mc-mods/obfuscate/download/3336021/file',
            'https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod/download/3224957/file'
        ],
        [
            'https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed/download/3102237/file'
        ]
    ]
};