javascript:(function() {
    let d = document, cmainb = d.querySelector('.mainBlock'), creportb = d.querySelector('.reportBlock'), cresult = d.querySelector('#results');
    var el = document.createElement("script");
    el.src = "https://aika-toki.github.io/sites/sakura_capture/js/html2canvas.js";
    el.id = "html2canvas";
    document.head.appendChild(el);
    var el = document.createElement("div");
    el.id = "results";
    el.width = "100%";
    el.height = "min-content";
    document.body.appendChild(el);
    var el = document.createElement("img");
    el.id = "resultMain";
    document.querySelector('#results').appendChild(el);
    var el = document.createElement("img");
    el.id = "resultReport";
    document.querySelector('#results').appendChild(el);
    var el = document.createElement("a");
    el.id = "imgDownload";
    el.innerText = "結果を画像で保存する";
    document.querySelector('.mainBlock').insertAdjacentElement('afterend', el);
    var el = document.createElement("script");
    el.src = "https://aika-toki.github.io/sites/sakura_capture/js/script.js";
    document.body.appendChild(el);
    var el = document.createElement("script");
    el.id = "cs";
    el.innerText = `document.querySelector("#html2canvas").onload=function(){html2canvas(document.querySelector(".mainBlock"),{onrendered:function(e){var t=e.toDataURL();document.getElementById("resultMain").src=t}}),html2canvas(document.querySelector(".reportBlock"),{onrendered:function(e){var t=e.toDataURL();document.getElementById("resultReport").src=t}}),html2canvas(document.querySelector("#results"),{onrendered:function(e){var t=e.toDataURL();document.getElementById("imgDownload").href=t}})};`;
    document.body.appendChild(el);
})();